# Firmware Version
export PRJ_VERSION = 0x00000001

# Define target output
target: gui

# Define target part
export PRJ_PART = XCKU040-FFVA1156-2-E

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
